package com.myspace.spectrum;

import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Appointment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean scheduled;
	private java.util.Date date;
	private com.myspace.spectrum.Facility facility;
	private java.lang.Long daysToAppointment;

	private java.lang.Boolean cancellationOffer;

	private java.lang.Boolean valetServicesNotification;

	public Appointment() {
	}

	public java.lang.Boolean getScheduled() {
		return this.scheduled;
	}

	public void setScheduled(java.lang.Boolean scheduled) {
		this.scheduled = scheduled;
	}

	public java.util.Date getDate() {
		return this.date;
	}

	public void setDate(java.util.Date date) {
		this.date = date;
	}

	public com.myspace.spectrum.Facility getFacility() {
		return this.facility;
	}

	public void setFacility(com.myspace.spectrum.Facility facility) {
		this.facility = facility;
	}

	public java.lang.Long getDaysToAppointment() {
		LocalDate today = LocalDate.now();
		LocalDate appointmentDate = this.date.toInstant()
				.atZone(ZoneId.systemDefault()).toLocalDate();
		return ChronoUnit.DAYS.between(today, appointmentDate);
	}

	public void setDaysToAppointment(java.lang.Long daysToAppointment) {
		this.daysToAppointment = daysToAppointment;
	}

	public java.lang.Boolean getCancellationOffer() {
		return this.cancellationOffer;
	}

	public void setCancellationOffer(java.lang.Boolean cancellationOffer) {
		this.cancellationOffer = cancellationOffer;
	}

	public java.lang.Boolean getValetServicesNotification() {
		return this.valetServicesNotification;
	}

	public void setValetServicesNotification(
			java.lang.Boolean valetServicesNotification) {
		this.valetServicesNotification = valetServicesNotification;
	}

	public Appointment(java.lang.Boolean scheduled, java.util.Date date,
			com.myspace.spectrum.Facility facility,
			java.lang.Long daysToAppointment,
			java.lang.Boolean cancellationOffer,
			java.lang.Boolean valetServicesNotification) {
		this.scheduled = scheduled;
		this.date = date;
		this.facility = facility;
		this.daysToAppointment = daysToAppointment;
		this.cancellationOffer = cancellationOffer;
		this.valetServicesNotification = valetServicesNotification;
	}

}