package com.myspace.spectrum;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CancellationOffer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;

	public CancellationOffer() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public CancellationOffer(java.lang.String id) {
		this.id = id;
	}

}