package com.myspace.spectrum;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Facility implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean hasValet;

	public Facility() {
	}

	public java.lang.Boolean getHasValet() {
		return this.hasValet;
	}

	public void setHasValet(java.lang.Boolean hasValet) {
		this.hasValet = hasValet;
	}

	public Facility(java.lang.Boolean hasValet) {
		this.hasValet = hasValet;
	}

}