package com.myspace.spectrum;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class One_day_before_scheduled_appointment
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;

	public One_day_before_scheduled_appointment() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public One_day_before_scheduled_appointment(java.lang.String id) {
		this.id = id;
	}

}