package com.myspace.spectrum;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Patient_admitted_to_hospital implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;

	public Patient_admitted_to_hospital() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public Patient_admitted_to_hospital(java.lang.String id) {
		this.id = id;
	}

}