package com.myspace.spectrum;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Patient Has Used Portal")
public class PatientHasUsedPortal implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public PatientHasUsedPortal() {
	}

}