package com.myspace.spectrum;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Patient implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer age;

	private java.lang.Boolean isPregnant;

	public Patient() {
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Boolean getIsPregnant() {
		return this.isPregnant;
	}

	public void setIsPregnant(java.lang.Boolean isPregnant) {
		this.isPregnant = isPregnant;
	}

	public Patient(java.lang.Integer age, java.lang.Boolean isPregnant) {
		this.age = age;
		this.isPregnant = isPregnant;
	}

}